"use client";

// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* header 追加 */}
        <header className=" bg-slate-600 p-4 ">
          <div className="flex justify-between mx-auto container items-center">
            <Link href="/" className="header-link">
              <h1 className="text-2xl text-white font-semibold">Blog</h1>
            </Link>
            <div className="flex ">
              <Link href="/admin/posts" className="header-link">
                <p className="text-base text-white mx-5">管理画面</p>
              </Link>

              <Link href="/contact" className="header-link">
                <p className="text-base text-white  ">お問い合わせ</p>
              </Link>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
